name: Lint and test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        python-version:
          - "2.6"
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10-dev"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip version
      run: |
        python -m pip install -U pip

    - run: python -V
    - run: pip -V
    - run: pip install -e .

    - name: Lint
      continue-on-error: true
      # run: flake8 pdfx tests setup.py --exclude="pdfx/libs,pdfx/extractor.py"
      run: flake8 pdfx tests setup.py

    - name: Run the test suite
      run: py.test --strict --capture=no tests
